security:
    firewalls:
        main: # <-- nom du firewall
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                 path: logout
                 target: blog_homepage

    providers:
        main_provider:
            entity:
                class:    BlogBundle:Users
                property: username

    encoders:
        BlogBundle\Entity\Users:
            algorithm: bcrypt
            cost: 10

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/redaction, roles: ROLE_REDACTOR }

    role_hierarchy:
        ROLE_REDACTOR: ROLE_USER
        ROLE_ADMIN: ROLE_REDACTOR
