<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function lesCinqDerniersArticles($resultnumber)
    {
        $qd = $this->createQueryBuilder('e');
        $qd ->addOrderBy('e.dateCreation','DESC');
        $query = $qd->getQuery();

        $query->setMaxResults($resultnumber);
        $articles = $query->getResult();
        return $articles;
    }
}
